"""initial tables

Revision ID: dfd00cee16c5
Revises: 
Create Date: 2025-12-11 14:33:50.618205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfd00cee16c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('uuid', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('places',
    sa.Column('uuid', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cidade', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('uuid', sa.String(length=45), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('shows',
    sa.Column('uuid', sa.String(length=45), nullable=False),
    sa.Column('show_date', sa.Date(), nullable=True),
    sa.Column('show_hour', sa.Time(), nullable=True),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('places_uuid', sa.String(length=45), nullable=True),
    sa.Column('clients_uuid', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['clients_uuid'], ['clients.uuid'], ),
    sa.ForeignKeyConstraint(['places_uuid'], ['places.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('paids',
    sa.Column('uuid', sa.String(length=45), nullable=False),
    sa.Column('show_uuid', sa.String(length=45), nullable=True),
    sa.Column('date_paid', sa.DateTime(), nullable=True),
    sa.Column('paid_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['show_uuid'], ['shows.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paids')
    op.drop_table('shows')
    op.drop_table('users')
    op.drop_table('places')
    op.drop_table('clients')
    # ### end Alembic commands ###
